### ISSUE TITLE
could not generate dist result for trees

### ISSUE THREAD

**Issue by zhangting1991** [pangenome/pggb-paper#1]
In the Phylogeny.md file, it says to use 'odgi path' to generate *dist.tsv, and then use this *dist.tsv to analyze phylogenetic tree. However, when I use 'odgi paths -i xx.og -t 2 >dist.tsv', nothing happens to dist.tsv, and I saw that the odgi paths manual says 'Interrogate the embedded paths of a graph. Does not print anything to stdout by default!'. Then I tried 'odgi paths -i xx.og -t 2 -o dist.og', but no dist.og was generated. So I am very confused. I want to generate a phylogenetic tree after the pggd graph, what should I do next?

**Comment by AndreaGuarracino** [comment]
@zhangting1991, I've updated the workflows. Now the distances for the trees are computed with `odgi similarity`!
